name: Android Build & Export APK/AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'  # You can adjust the Java version if needed

      - name: Set up Fastlane
        run: gem install fastlane

      - name: Decode API Key for Google Play
        env:
          GOOGLE_PLAY_API_KEY: ${{ secrets.GOOGLE_PLAY_API_KEY }}
        run: echo "$GOOGLE_PLAY_API_KEY" | base64 --decode > fastlane/GooglePlayAuth.json

      - name: Build APK/AAB
        run: ./gradlew assembleRelease  # Use 'bundleRelease' if you want an AAB

      - name: Upload to Google Play
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}  # Google Play service account key file
        run: fastlane supply --aab ./app/build/outputs/bundle/release/app-release.aab --json_key fastlane/GooglePlayAuth.json --package_name com.yourapp.package
